### ISSUE TITLE
Add documentation to set LD_LIBRARY_PATH to libelf++.so and libdwarf++.so in coz/deps

### ISSUE THREAD

**Issue by santoshn** [plasma-umass/coz#101]
We were noticing weird segmentation faults when the system already has libelf/libdwarf installed but the LD_LIBRARY_PATH does not point to the coz/deps directory.

I think adding instructions about explicitly setting LD_LIBRARY_PATH to  coz/deps/libelfin/dwarf and coz/deps/libelfin/elf is helpful.

**Comment by ccurtsinger** [comment]
This should no longer be necessary because coz builds using the system-installed libelf++ and libdwarf++ instead of building them locally.
