### ISSUE TITLE
Issue compiling on ARM

### ISSUE THREAD

**Issue by WilliamASumner** [plasma-umass/coz#105]
I've tried compiling with clang (version 6.0.0) on an ODROID XU3 (the architecture is armv7l) and everything compiles just fine, however when I go to run it I get the following error:
```
[ 6325.439410] [c5] Alignment trap: not handling instruction e1932f9f
[ 6325.446696] [c5] alignment exception (0x011) at 0xb6f7b061
```
Doing a backtrace on the core reveals an error at `libcoz/ccutil/static_map.h:17`, but the actual error occurs some where in `<atomic>`. I'm not sure if it's my gcc/clang setup or if there's an issue within coz - any insight would really be appreciated.

edit: fixed a typo and added clang version number

**Comment by WilliamASumner** [comment]
It was an issue within my setup - I'm not quite sure why clang was having trouble, but trying it again using just gcc and rearranging the elf and dwarf linker flags in `libcoz/Makefile` solved the problem.

**Comment by emeryberger** [comment]
Do you mind sharing the re-arranged flags? Thanks!

**Comment by WilliamASumner** [comment]
Sure thing, in `libcoz/Makefile` I changed 
`LIBS     := dl rt pthread` 
to 
`LIBS     := dl rt pthread elf++ dwarf++`
