### ISSUE TITLE
coz uses python 3

### ISSUE THREAD

**Issue by emeryberger** [plasma-umass/coz#106]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=936336

**Comment by ccurtsinger** [comment]
I dropped the link to the other bug from 2017 (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=854031). Peter said it was resolved, and I've changed the build process to use the system libelfin so it's not really relevant anymore.

**Comment by Recursing** [comment]
Should the README.md be changed to replace the requirement of python 2.7 with python 3?
