### ISSUE TITLE
Show enough of file path to be unique in plot title

### ISSUE THREAD

**Issue by fitzgen** [plasma-umass/coz#114]
Rust uses a whole lot of `<something>/src/lib.rs` and `<something>/mod.rs` file paths, and `coz`'s default of showing only the file name makes the results pretty hard to interpret:

![Screenshot_2019-09-24 coz plot](https://user-images.githubusercontent.com/74571/65542760-a1bd3a00-dec4-11e9-8117-9969a1c95fcc.png)

It would be cool if it showed enough of the end of the path to uniquely identifiy the file, for example:

| Full File Path                         | Display           |
|----------------------------------------|-------------------|
| /home/fitzgen/walrus/src/lib.rs        | walrus/src/lib.rs |
| /home/fitzgen/walrus/src/passes/mod.rs | passes/mod.rs     |
| /home/fitzgen/rayon/src/lib.rs         | rayon/src/lib.rs  |
| /home/fitzgen/rayon/src/spawner/mod.rs | spawner/mod.rs    |

Would also be awesome if it could show the full path on hover / in the alt text.

**Comment by ArniDagur** [comment]
This is perhaps off topic, but it would be cool to see the patches you made to profile these projects with `coz`. I'm still having difficulties picking the best spots to put progress points.

**Comment by fitzgen** [comment]
>  it would be cool to see the patches you made to profile these projects with `coz`

Here you go: https://github.com/fitzgen/walrus/commit/204139326ffc47cc1431139765d5f075fd631c0c

Good luck!

**Comment by camchenry** [comment]
I can work on this! I have seen the same issue with profiling Rust code also.

**Comment by bjorn3** [comment]
@camchenry: #123 has already been opened.

**Comment by camchenry** [comment]
Would it not be better to have both? You could toggle to show the full path, hover to see the full path, and also have a trimmed path by default.

**Comment by camchenry** [comment]
I think that I have at least a better version of the current file name selection algorithm. 

Before (master):
![image](https://user-images.githubusercontent.com/1514176/66222410-18b1ba00-e69f-11e9-82e7-6af86341f9f9.png)



After:
![image](https://user-images.githubusercontent.com/1514176/66222371-ffa90900-e69e-11e9-933a-b7ea138ef76e.png)

This is the second version of the algorithm, and while it will definitely not give the shortest possible unique path, it should almost always give at least a unique path. The way it works is pretty simple (barring a few special cases):

1. Get list of all paths with only the last part.
2. Check if those paths are unique.
3. If not, increase the number of parts to include and repeat.

**Comment by camchenry** [comment]
Additionally, all of the plot titles have a `title` attribute with the full name of the path, so you can hover to see the full path.

![image](https://user-images.githubusercontent.com/1514176/66223217-f0c35600-e6a0-11e9-9acd-6e49e540c782.png)
