### ISSUE TITLE
Show function symbol in addition to source location

### ISSUE THREAD

**Issue by fitzgen** [plasma-umass/coz#115]
`coz` is reporting that speeding up a certain source location could improve my program's throughput, however the source location is inside a generic, monomorphized function, and it isn't clear to me which instantiation of this generic function is the one that matters, if some do, or if all of them do.

If I had the function symbol, I would be able to tell which instantiation `coz` is considering.

**Comment by ccurtsinger** [comment]
This will happen as part of #59, when adding support for larger code fragments like functions or basic blocks. As it is now, the profile is really just telling you about the effect of speeding up a particular line, not the whole function.
