### ISSUE TITLE
Cmake support

### ISSUE THREAD

**Issue by xd009642** [plasma-umass/coz#117]
If there was a FindCoz.cmake or CozConfig.cmake that was installed when make install was ran (if cmake is installed) it would make using coz a lot easier with cmake projects. 

I've not written either of them myself before but I'd be willing to learn if no-one else with more experience is available to help and if the addition would be welcomed :smile:

**Comment by ccurtsinger** [comment]
That sounds useful, but I also do not use cmake so I wouldn't be the right one to implement it. I'd be happy to accept a pull request with this change.

**Comment by xd009642** [comment]
I do use cmake just never this part of it. I'm working on it now just need to test it and make sure it's idiomatic 👍

**Comment by xd009642** [comment]
I've submitted a pr for this in #129

**Comment by ccurtsinger** [comment]
Fixed in #129
