### ISSUE TITLE
Support for profiling the Linux kernel itself

### ISSUE THREAD

**Issue by felipebalbi** [plasma-umass/coz#124]
Have you guys considered the possibility of "cozing" (heh) the Linux kernel itself? If `coz` could get an input file with metrics for processing after the fact, we could have some debug option in Linux generate output that `coz` could run post processing.

**Comment by ArniDagur** [comment]
See #3

**Comment by ccurtsinger** [comment]
This would be a nice feature and it's on my wishlist, but it's not likely to be something we'll get to soon.
