### ISSUE TITLE
`coz run` produces no output if interrupted by Ctrl-C

### ISSUE THREAD

**Issue by vadimcn** [plasma-umass/coz#143]
It seems that `coz run ...` saves data only when profiling target reaches the end of main().

Some programs are designed to exit only when interrupted, or take a long time to terminate.   It would be nice if Coz could deal with signals, exit(), etc, and save the data collected up to that point.

**Comment by antoyo** [comment]
Not sure about that.
It seems to periodically write to `profile.coz`.

The thing I saw, though, is that my server was missing latency points and I needed to run it for a long time in order to generate an actual graph.

**Comment by emeryberger** [comment]
Coz definitely periodically writes to `profile.coz`. While Coz works without progress points, it's really best to use them.
