### ISSUE TITLE
coz_plot: Better-looking graphs 

### ISSUE THREAD

**Issue by jvilk** [plasma-umass/coz#15]
I wanted coz_plot to produce graphs like Figure 2 in the paper, but it's ugly by default. :(

Please fix.

**Comment by ccurtsinger** [comment]
See http://plasma-umass.github.io/coz and let me know what you think. Feedback would be appreciated?

Also, if you know a painless way to avoid JS integer overflow issues, let me know. Adding together memcached progress point counters just turns into NaNs.

**Comment by jvilk** [comment]
You'd probably want to use a bignum library. I'd recommend [bignumber.js](https://github.com/MikeMcl/bignumber.js/) if this seems like a useful option.
