### ISSUE TITLE
Tag new release

### ISSUE THREAD

**Issue by llvilanova** [plasma-umass/coz#159]
Please tag current master for a new release, so I can try reviving Debian's package.

**Comment by emeryberger** [comment]
https://github.com/plasma-umass/coz/releases/tag/0.2.2

**Comment by llvilanova** [comment]
Great, thanks. Waiting for libelfin's release tag so both packages can be updated.

**Comment by llvilanova** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=936336#59
