### ISSUE TITLE
Fix integer overflow in plotting interface

### ISSUE THREAD

**Issue by ccurtsinger** [plasma-umass/coz#17]
The new profiler interface at http://plasma-umass.github.io/coz cannot plot the memcached results because the sum over progress point visits overflows JavaScript integers.

**Comment by jvilk** [comment]
I recommended the use of [bignumber.js](https://github.com/MikeMcl/bignumber.js/) to avoid overflows. I've used it previously, and can vouch that it actually works well. You can pass it numbers represented as strings, too, to overcome JavaScript integer limitations.
