### ISSUE TITLE
Would you take a PR to change build to CMake?

### ISSUE THREAD

**Issue by rconde01** [plasma-umass/coz#170]
As a first step to building on windows it would be good to change the build to CMake. Would you take that PR?

**Comment by emeryberger** [comment]
Sure, as long as it fully replaces the functionality of the existing Makefile!

**Comment by klimkin** [comment]
This could be a good starting point: https://github.com/conan-io/conan-center-index/pull/3282
- The CMakeLists.txt builds everything except benchmarks. 
- Will need to clarify lookup for `libelfin` libraries, if building outside of Conan environment

Another option is to use Conan+CMake, this would simplify dependency management from libelfin.

**Comment by klimkin** [comment]
https://github.com/plasma-umass/coz/pull/178

**Comment by klimkin** [comment]
This can be closed now.
