### ISSUE TITLE
Look for libcoz.so in standard library locations

### ISSUE THREAD

**Issue by jonhoo** [plasma-umass/coz#19]
The coz Python wrapper sets `LD_PRELOAD` to be the directory name of where it is located. In system installs, this will not be the case. The Python executable will be in `/usr/bin`, whereas `libcoz.so` will be in `/usr/lib`. It would be better if `LD_PRELOAD` was left empty if it is passed in as empty.

**Comment by ccurtsinger** [comment]
Coz must be injected into the application using LD_PRELOAD to support unmodified executables. You should never actually link a program against libcoz.so, so placing it in a standard library directory could lead to accidental inclusion. The lines you changed just make sure injecting libcoz doesn't clobber any LD_PRELOADs provided by the user.

**Comment by jonhoo** [comment]
Ah, that makes sense. Still seems unfortunate that `libcoz.so` needs to be located in the same directory as the coz binary. At the very least, making coz resolve symlinks before using the path (so that coz can be symlinked into `/usr/bin`) would help. A better solution might be to have the path to `libcoz.so` set during `make` (effectively changing `coz_runtime` in the coz executable).

**Comment by jonhoo** [comment]
`/usr/share/coz/libcoz.so` might be a good default.
