### ISSUE TITLE
Optimize total programm run time

### ISSUE THREAD

**Issue by freemin7** [plasma-umass/coz#199]
Assuming i have a particular program with particular inputs with a total run-time want to optimize
```
./executeable work_file
```
Do i really need to recompile the executable and add a progress point before the successful exit and loop the executetable using something like bash

```
coz run --- bash -c "for i in {1..10000}; do ./executeable work_file; done;" 
```
Or is there a more elegant way?

**Comment by emeryberger** [comment]
You could of course also have the code execute a loop comprising the whole program, but if you don't want to do that, what you propose would work. Ideally you'd have some individual thing that you really want to have happen more frequently (so you'd place a throughput progress point) or a begin-end pair which you'd like to take less time (which would call for latency progress points).

**Comment by emeryberger** [comment]
Let's move this to discussions.

**Comment by freemin7** [comment]
Where do these happen?
