### ISSUE TITLE
How do I get the .coz files for the benchmarks?

### ISSUE THREAD

**Issue by jonhoo** [plasma-umass/coz#20]
After I `make bench` for one of the benchmarks in `benchmarks/`, where is the profiling data stored?

**Comment by ccurtsinger** [comment]
The `make bench` target jumps into each benchmark directory before running the program with coz. By default, coz will drop the profile.coz file in the current directory. So, look in benchmarks/<bench_name>/

**Comment by jonhoo** [comment]
Ah, this was caused by me simply removing `LD_PRELOAD` in #23, which obviously means Coz won't run at all.
