### ISSUE TITLE
Coz does not support OSX

### ISSUE THREAD

**Issue by andrewtremblay** [plasma-umass/coz#21]
This project has amazing potential as an additional tool for Xcode, which [uses clang](https://gist.github.com/yamaya/2924292) for compiling iOS and Mac apps. However, Xcode can only be run on Apple operating systems. Is there any plan (or guide) to getting this code to work on Windows/Mac? So far my attempts have not been successful.

**Comment by ccurtsinger** [comment]
OSX support would be great, but there are some limitations in the sampling APIs available for on macs. This is on the wish-list, but porting would require a new sampling mechanism for Coz. Mapping instructions to source lines relies on debug information, and Coz currently only supports ELF files. Mach-O support shouldn't be too hard to implement, but it isn't done yet.

**Comment by llvilanova** [comment]
For the record, this is related to #81.
