### ISSUE TITLE
Dependencie "libelfin" doesn't compile

### ISSUE THREAD

**Issue by A-Grunder** [plasma-umass/coz#234]
The dependency [https://github.com/antoyo/libelfin/tree/master](https://github.com/antoyo/libelfin/tree/master) has a problem in this file : [https://github.com/antoyo/libelfin/blob/master/elf/data.hh](https://github.com/antoyo/libelfin/blob/master/elf/data.hh) at line 556. The `const` at the end must be removed in order to compile.

**Comment by camelid** [comment]
The fix for this issue was merged upstream. Try using https://github.com/aclements/libelfin instead.
