### ISSUE TITLE
Mismatch of macro names in the documentation and in the include file

### ISSUE THREAD

**Issue by fedorova** [plasma-umass/coz#32]
Guys, your documentation tells to use COZ_* macros (e.g., COZ_PROGRESS, COZ_BEGIN, etc.), but in the coz.h file they are named as CAUSAL_*.

**Comment by emeryberger** [comment]
Thanks, Sasha. Fixed with https://github.com/plasma-umass/coz/commit/77d5fcd25a676352ed3bb30f446021680b488bb7.
