### ISSUE TITLE
why cannot see result plot?

### ISSUE THREAD

**Issue by XuYunnan** [plasma-umass/coz#36]
I run     coz run --- "some command"      in your benchmarks , and get profile.coz file, but when I upload profile.coz to http://plasma-umass.github.io/coz/ , I can not see result plot, your Sample Profiles is ok, but upload files is not. 

And is there any way to view a result plot local?

Thank you.

**Comment by XuYunnan** [comment]
OK, I found it was a javascript bug:
d3-tip.min.js:1 Uncaught TypeError: Cannot read property 'tagName' of null

I used chrome.
so how to fix it?

**Comment by ccurtsinger** [comment]
How many times did you run your application with coz? Did you remember to insert progress points?
This is a known issue (see #25) for profiles that do not contain enough data to generate a plot.
