### ISSUE TITLE
Is it possible to profile background processes?

### ISSUE THREAD

**Issue by voidbag** [plasma-umass/coz#45]
I use distributed file system.
After I know this tool, I wonder if I'm able to profile background process of distributed file system, using this tool.
I want to profile the background process which handles I/O, when some I/O requests are issued.

Could this tool be used for the above use case?

Thank you

**Comment by ccurtsinger** [comment]
You could certainly start the background process with coz. I haven't tested it, but I expect it should work. Have you tried this yet?

**Comment by ccurtsinger** [comment]
Since this should work and I haven't heard back, I'm closing the issue. Please reopen if you find a background process that does not work with coz.
