### ISSUE TITLE
Compiler complain about check of non-null sig in sigwait()

### ISSUE THREAD

**Issue by petterreinholdtsen** [plasma-umass/coz#53]
When building the source I see this compiler working:

```
libcoz.cpp:439:10: warning: nonnull parameter 'sig' will evaluate to 'true' on first
      encounter [-Wpointer-bool-conversion]
      if(sig) *sig = result;
      ~~ ^~~
```

It is the only warning in the code.  The reason for the warning is this definition in /usr/include/signal.h:

```
/* Select any of pending signals from SET or wait for any to arrive.

   This function is a cancellation point and therefore not marked with
   __THROW.  */
extern int sigwait (const sigset_t *__restrict __set, int *__restrict __sig)
     __nonnull ((1, 2));
```

Why is the sig argument checked for NULL in the replacement implementation of sigwait()?
As far as I can see from the POSIX / Open Group definition sig is not supposed to be NULL, see http://pubs.opengroup.org/onlinepubs/009695399/functions/sigwait.html .

I suspect the code should look like this instead:

```
 
diff --git a/libcoz/libcoz.cpp b/libcoz/libcoz.cpp
index 83f4c51..db72cfb 100644
--- a/libcoz/libcoz.cpp
+++ b/libcoz/libcoz.cpp
@@ -436,7 +436,7 @@ extern "C" {
       return errno;
     } else {
       // If the sig pointer is not null, pass the received signal to the caller
-      if(sig) *sig = result;
+      *sig = result;
       return 0;
     }
   }
```

**Comment by ccurtsinger** [comment]
If `__USE_POSIX_199309` is defined, only the `set` parameter to `sigwat` is marked nonnull. I am not seeing this warning, so I can't try out fixes. Would changing the line you identified to `if(sig != NULL) *sig = result;` resolve the warning?

**Comment by petterreinholdtsen** [comment]
[Charlie Curtsinger]
> If `__USE_POSIX_199309` is defined, only the `set` parameter to
> `sigwat` is marked nonnull. I am not seeing this warning, so I can't
> try out fixes.

Hm, that is not the case for glibc version 2.19 I am using in Debian
Jessie.

> Would changing the line you identified to `if(sig != NULL) *sig =
> result;` resolve the warning?

Nope, already tried that.

-- 
Happy hacking
Petter Reinholdtsen
