### ISSUE TITLE
Include profile analysis website source in main repository

### ISSUE THREAD

**Issue by petterreinholdtsen** [plasma-umass/coz#55]
Hi.  Where can I find the source of the http://plasma-umass.github.io/coz/ web site?  It seem unable to do anything with the profile.coz I created from running scrub, and I would like to understand why.  Also, I would like to make sure it is possible to analyze the profile results without depending on external Internet access.

**Comment by ccurtsinger** [comment]
The code for the site is in the `gh-pages` branch on the main repository, and should work just fine when run locally. If your profile doesn't do anything, it's probably too small. Fixing this is an outstanding issue.

**Comment by petterreinholdtsen** [comment]
[Charlie Curtsinger]
> The code for the site is in the `gh-pages` branch on the main
> repository, and should work just fine when run locally. If your
> profile doesn't do anything, it's probably too small. Fixing this is
> an outstanding issue.

Aha.  That might be true.  The lack of feedback confused me.  The scrub
run was fairly quick, that is true.

The code in gh-pages seem to work fairly standalone.  That is good.
Could you include that code if you make release tarballs or release tags
for use with Debian packaging, to make sure the analyzer code will be
included in the Debian package?
-- 
Happy hacking
Petter Reinholdtsen

**Comment by emeryberger** [comment]
+1 on including the code in the package and the repo.

**Comment by ccurtsinger** [comment]
It looks like this Gist thread has some methods that would make it easy to keep the profile display page in sync with the `gh-pages` branch: https://gist.github.com/cobyism/4730490

**Comment by petterreinholdtsen** [comment]
Any news on this?

Btw, I was wrong when I said "the code in gh-pages seem to work fairly standalone".  The JavaScript code require Internet access to work, as it include script fragments from various sources.  I discovered this when trying to profile using coz when offline.  Please make the web pages included in the source work without Internet access.

Also, note that according to the Debian package build checking tools, several of the scripts in the gh-pages branch are obfuscated/unreadable and missing source:

```
E: coz-profiler source: source-is-missing viewer/profiles/swaptions.coz.js
E: coz-profiler source: source-is-missing viewer/profiles/sqlite.coz.js
E: coz-profiler source: source-is-missing viewer/profiles/memcached.coz.js
E: coz-profiler source: source-is-missing viewer/profiles/fluidanimate.coz.js
E: coz-profiler source: source-is-missing viewer/profiles/ferret.coz.js
E: coz-profiler source: source-is-missing viewer/profiles/dedup.coz.js
E: coz-profiler source: source-is-missing viewer/profiles/blackscholes.coz.js
E: coz-profiler source: source-is-missing viewer/lib/science/science.v1.min.js
```

Please provide the source of these scripts, to allow humans to update them when needed.

**Comment by llvilanova** [comment]
Is coz interested in merging the contents of the gh-pages branch into master? If so I can cook a pull request.
