### ISSUE TITLE
Add `cleandeps` target to rebuild dependencies

### ISSUE THREAD

**Issue by petterreinholdtsen** [plasma-umass/coz#56]
I ran into a problem with the build today.  I tried to rebuild the coz package using the new GCC compiler in Debian, but could not get the binary to work because it was missing a symbol in elf::elf.  I tracked down the problem to the fact that libelfin had not been rebuilt with the new compiler, causing the required symbol to be missing due to different mangling of the function.

Please change the build system to clean the libelfin directory when doing 'make clean'.

**Comment by ccurtsinger** [comment]
I'm assuming this was the ABI-breaking change to `gcc` from a year or so ago. There's really never any other reason to rebuild libelfin, so I don't think this should be part of the `clean` target. I'd accept a pull request for a `cleandeps` target, though.

**Comment by petterreinholdtsen** [comment]
[Charlie]
> I'm assuming this was the ABI-breaking change to `gcc` from a year or
> so ago. There's really never any other reason to rebuild libelfin, so
> I don't think this should be part of the `clean` target. I'd accept a
> pull request for a `cleandeps` target, though.

I use Debian Stable on my work machine and build the code for Debian
Unstable in a chroot.  Every time I switch between them, I run into the
problem.  So for me, I need to rebuild libelfin quite often.

The general practice with free software is to have a 'distclean' target
that bring the source back to the state it had when being distributed.
I'll see if I can prepare a pull request to create such target for coz.
It would solve my problem as the Debian package build system will call
it automatically before compiling.

--
Happy hacking
Petter Reinholdtsen
