### ISSUE TITLE
Push libelfin changes upstream

### ISSUE THREAD

**Issue by ccurtsinger** [plasma-umass/coz#58]
Submit a pull request to get libelfin to build with `-fPIC` or to build a separate shared library target.

**Comment by ccurtsinger** [comment]
Submitted pull request aclements/libelfin#8.

**Comment by petterreinholdtsen** [comment]
Is libelfin still an active project?  The response time seem to be rather relaxed.

**Comment by ccurtsinger** [comment]
The pull request was just merged, so I'm closing the issue.
