### ISSUE TITLE
Set up build testing

### ISSUE THREAD

**Issue by paulmenzel** [plasma-umass/coz#70]
With merge requests #63 and #67, it’d be great if build testing could be set up to make sure that the code builds fine with GCC and Clang, and the tests pass (there is just one at the moment).

[Travis CI](https://travis-ci.org/) has a GitHub integration so could be used for that.

**Comment by petterreinholdtsen** [comment]
Perhaps start with the simple test I suggested, and extend it as you got time?  It would ensure the generated library isn't completely broken. :)

**Comment by petterreinholdtsen** [comment]
Hi.  The automatic testing during build have already made sure broken packages do not make it into any debian architecture.  Any hope to have such feature in the default build?

**Comment by ccurtsinger** [comment]
Coz now uses TravisCI to build with both gcc and clang, and runs each of the benchmarks with coz.
