### ISSUE TITLE
Port to non-Linux platforms?

### ISSUE THREAD

**Issue by petterreinholdtsen** [plasma-umass/coz#81]
At the moment coz fail to build on non-Linux platforms like kfreebsd and hurd in Debian, because it uses the API provided in <linux/perf_event.h>.  Are there any plans to port coz to non-linux platforms?

**Comment by petterreinholdtsen** [comment]
Ah, forgot to link to the Debian bug about this, https://bugs.debian.org/844024 .  See also the autobuilder
status on https://buildd.debian.org/status/package.php?p=coz-profiler&suite=unstable .

**Comment by ccurtsinger** [comment]
This would be a major undertaking, as interacting with performance counters is tightly integrated with coz's functionality. I'm unfamiliar with kfreebsd and hurd's performance counter interfaces, so this is probably something someone else would need to take care of.

**Comment by petterreinholdtsen** [comment]
[Charlie Curtsinger]
> This would be a major undertaking, as interacting with performance
> counters is tightly integrated with coz's functionality. I'm
> unfamiliar with kfreebsd and hurd's performance counter interfaces, so
> this is probably something someone else would need to take care of.

OK.  We will limit the Debian package to linux architectures for now,
then. :)
-- 
Happy hacking
Petter Reinholdtsen
