### ISSUE TITLE
portability: Replace ccutil::spinlock with std::mutex

### ISSUE THREAD

**Issue by llvilanova** [plasma-umass/coz#83]
Since coz's makefiles already set the C++ standard to C++11, one could use standard std::mutex instead of the handcrafted spinlock class in ccutil. As it turns out, ccutil's spinlock has inline assembly and only works for x86.

**Comment by llvilanova** [comment]
If this is desired, I can work on a merge request. I'm just not sure how critical and short-lived are the sections these spinlocks are guarding.

**Comment by emeryberger** [comment]
Note that Coz needs to interpose on locks (at the pthread API level). It thus can't use those locks internally.

**Comment by emeryberger** [comment]
However, it might be possible to use a spinlock from the standard library as long as it itself does not invoke any pthreads APIs.

**Comment by llvilanova** [comment]
I see; AFAIK, there is no spinlock in the standard C++ library. How critical are the sections guarded by these locks? Debian is currently patching ccutil to use std::this_thread::yield() whenever "pause" is not available (ends up calling sched_yield()). If the code is critical we can just drop pause, and let the processor choke on speculative memory accesses.

**Comment by llvilanova** [comment]
BTW, if by interpose you mean library symbol interposition, you can call the original (non-interposed) symbol from within libcoz to avoid acting on it. I don't know coz's design, so I'm not sure if that'd have any effects on the sampling (i.e., sampling calls to pthread_mutex_lock from within libcoz).

**Comment by llvilanova** [comment]
I just realized ccurtsinger/ccutil#3 discusses this problem, and provided a temporary patch without yield() there.

I'm waiting to know if coz's real::pthread_muted_lock/unlock can be used instead, before closing this issue; if threads are expected to wait on these locks, not using a proper kernel-scheduled mutex might severely affect the profiling results.

**Comment by ccurtsinger** [comment]
The spinlock is required because we cannot yield. This should not be replaced with any sort of standard synchronization operation unless it is guaranteed not to yield the CPU.
