### ISSUE TITLE
Checks always fail

### ISSUE THREAD

**Issue by llvilanova** [plasma-umass/coz#87]
Commit 61bb482 seems to introduce the error. Is there any simple work-around so that I can release a new snapshot in debian?

Maybe you could add a `.travis.yml` file to your repo to have commits checked for errors in the future: https://docs.travis-ci.com/user/getting-started/

**Comment by petterreinholdtsen** [comment]
The travis idea is mentioned in issue #70.

**Comment by ccurtsinger** [comment]
I don't have any problems running coz with this revision. Are you sure the program you were testing on has debug symbols available?

**Comment by petterreinholdtsen** [comment]
[Charlie Curtsinger]
> I don't have any problems running coz with this revision. Are you sure
> the program you were testing on has debug symbols available?

Are you saying 'make check' work for you?  It fail consistenly here like
this:

% make check
make -C libcoz check
make[1]: Entering directory '/home/pere/src/debian/pkg-coz/coz-profiler/libcoz'
[coz-profiler] Compiling x.c 
[coz-profiler] Linking libcoz.so 
printf "int main(int argc, char *argv[])\n{\nreturn (0);\n}\n" > x.c
gcc -Wl,-rpath,`pwd` -o x x.c libcoz.so -ldl || ( rm -f x x.c ; exit 1)
./x
[libcoz.cpp:100] bootstrapping coz
[inspect.cpp:327] Debug information was not found for any in-scope executables or libraries
Makefile:10: recipe for target 'check' failed
make[1]: *** [check] Aborted
make[1]: Leaving directory '/home/pere/src/debian/pkg-coz/coz-profiler/libcoz'
Makefile:10: recipe for target 'check' failed
make: *** [check] Error 2
%

Adding '-g' do not help:

diff --git a/libcoz/Makefile b/libcoz/Makefile
index 5de62fc..342c737 100644
--- a/libcoz/Makefile
+++ b/libcoz/Makefile
@@ -8,7 +8,7 @@ include $(ROOT)/common.mk
 
 check:: libcoz.so
        printf "int main(int argc, char *argv[])\n{\nreturn (0);\n}\n" > x.c
-       gcc -Wl,-rpath,`pwd` -o x x.c libcoz.so -ldl || ( $(RM) x x.c ; exit 1)
+       gcc -g -Wl,-rpath,`pwd` -o x x.c libcoz.so -ldl || ( $(RM) x x.c ; exit 1)
        ./x
        if grep -q time= profile.coz; then echo success: coz profiler ran as it should.; fi
        $(RM) -f x.c x profile.coz

--
Happy hacking
Petter Reinholdtsen

**Comment by ccurtsinger** [comment]
The issue was `make check` was running with libcoz linked directly into the program. I changed the target so it runs with the `coz` tool instead in revision f38f22e.
