### ISSUE TITLE
make fails on Linux Mint 18 x64

### ISSUE THREAD

**Issue by psteckler** [plasma-umass/coz#88]
I cloned the repo, installed `npm` and `nodejs`, and ran `make`, which failed with:

`$ make`
`npm install`
`> coz@1.0.0 prepublish /home/steck/coz/viewer`
`> tsc`
`/usr/bin/env: ‘node’: No such file or directory`

Here's the debug log. Maybe I need newer versions of npm and Node.js?

[npm-debug.txt](https://github.com/plasma-umass/coz/files/643220/npm-debug.txt)

**Comment by ccurtsinger** [comment]
I think ubuntu/mint renamed this tool from `node` to `nodejs`. Maybe the most reliable way to fix this issue is to compile the typescript source with `tsc` instead of a node-based builder.

**Comment by woonhak** [comment]
I had the same issue on Ubuntu 14.04.
To create symbolic link of 'node' to 'nodejs' can be a temporal fix.

`ln -s /usr/bin/nodejs /usr/bin/node`

**Comment by emeryberger** [comment]
How about adding an ad hoc check for nodejs, failing over to node? Ubuntu is an important platform, so we should support it.

**Comment by jvilk** [comment]
One solution is to [`apt-get install nodejs-legacy`](https://packages.debian.org/sid/nodejs-legacy) which does the right thing. It's in Debian, Ubuntu, and likely Mint as well.

**Comment by emeryberger** [comment]
Sounds great. I would be happy to merge a PR.

**Comment by ccurtsinger** [comment]
It seems that ubuntu now creates both `node` and `nodejs` executables transparently now, so this should no longer be an issue.
