### ISSUE TITLE
Unable to build Coz due to npm error on a Ubuntu machine

### ISSUE THREAD

**Issue by santoshn** [plasma-umass/coz#92]
I am trying to build the latest version of Coz on a Ubuntu Linux server. I get the following error when I do make.  Any suggestions on how I can address this?

uname -a for my machine gives the following string

"Linux <hostname> 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux"

npm install
npm http GET https://registry.npmjs.org/types/jquery
npm http GET https://registry.npmjs.org/types/d3
npm http GET https://registry.npmjs.org/types/bootstrap
npm http GET https://registry.npmjs.org/typescript
npm http 304 https://registry.npmjs.org/typescript
npm http 404 https://registry.npmjs.org/types/jquery
npm http 404 https://registry.npmjs.org/types/bootstrap
npm http 404 https://registry.npmjs.org/types/d3
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/share/npm/lib/cache.js:687:35)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/santosh/coz/coz-0.1.0/viewer
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type non_object_property_load
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/share/npm/lib/cache.js:687:35)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/santosh/coz/coz-0.1.0/viewer
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type non_object_property_load
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/share/npm/lib/cache.js:687:35)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/santosh/coz/coz-0.1.0/viewer
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type non_object_property_load
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/santosh/coz/coz-0.1.0/viewer/npm-debug.log
npm ERR! not ok code 0

**Comment by ccurtsinger** [comment]
What version of Ubuntu is this? I think there has been quite a bit of churn in `npm`, especially in the Ubuntu packages, so there may be a compatibility issue. As a quick workaround, you can remove `viewer` from line 2 in `Makefile` at the root and just use the online viewer at <http://plasma-umass.github.io/coz/>.

**Comment by jvilk** [comment]
@santoshn can you try updating NPM and trying again? Unfortunately, the fast pace of the JS ecosystem isn't very compatible with Debian's packaging system. :/

https://github.com/npm/npm/issues/4982#issuecomment-39272294

Let me know if it gives you further errors.
