### ISSUE TITLE
Segmentation fault on load

### ISSUE THREAD

**Issue by tomergibm** [plasma-umass/coz#94]
Hi.
Im encountering segmentation fault when loading a process after calling a function in libpthread.

Example:

Segmentation fault at 0x772699821
  0: /local/scratch/coz_static/libcoz/libcoz.so(_ZN8profiler8on_errorEiP9siginfo_tPv+0x84) [0x7f2e7268eff4]
  1: /lib64/libpthread.so.0(+0xf36f) [0x7f2e71e6136f]

Thanks.

**Comment by emeryberger** [comment]
Can you please send more details? Command-line parameters, system info, plus a way to reproduce the error.

**Comment by tomergibm** [comment]
the command line is as follows:
coz run --output /tmp/coz.$$ > /tmp/coz-out.$$ 2> /tmp/coz-err.$$ < /dev/null --- <executable>

I need to check about more details.

**Comment by emeryberger** [comment]
Try this instead (that is, put `yourProgram` before the redirects):

`coz run --output /tmp/coz.$$ --- ./yourProgram > /tmp/coz-out.$$ 2> /tmp/coz-err.$$`

**Comment by emeryberger** [comment]
Also, unable to reproduce this problem on Ubuntu.
