### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by petterreinholdtsen** [plasma-umass/coz#99]
Hi.  Are there still peope working on this project?  The bug fixing speed seem to have grind to a halt and commits barely make it to the repository.  Should I worry about the future maintenance of the Debian package?  Debian freezes soon for the new release, and we thus would need to support the package for three years forward.  This is a lot easier with an active upstream project.

**Comment by emeryberger** [comment]
Hi - @ccurtsinger might be a bit overwhelmed but I am still on board and will commit (no pun intended) to take the lead on ensuring commits get approved, etc.

**Comment by petterreinholdtsen** [comment]
[Emery Berger]
> Hi - @ccurtsinger might be a bit overwhelmed but I am still on board
> and will commit (no pun intended) to take the lead on ensuring commits
> get approved, etc.

Right.  I am more worried about who will actually create commits to fix
the registered issues, if for example a security issue or a fatal
problem should arrise the next few years.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by emeryberger** [comment]
Either @ccurtsinger or I will do this.
